-- AlterTable
ALTER TABLE "User" ADD COLUMN     "gpa_1_1" DOUBLE PRECISION NOT NULL DEFAULT -1,
ADD COLUMN     "gpa_1_2" DOUBLE PRECISION NOT NULL DEFAULT -1,
ADD COLUMN     "gpa_2_1" DOUBLE PRECISION NOT NULL DEFAULT -1,
ADD COLUMN     "gpa_2_2" DOUBLE PRECISION NOT NULL DEFAULT -1,
ADD COLUMN     "gpa_3_1" DOUBLE PRECISION NOT NULL DEFAULT -1;
